### ISSUE TITLE
diff DB with data

### ISSUE THREAD

**Issue by Mamol27** [tbrugz/sqldump#2]
Hi! 
When I tried do diff with data for tables, where i changed columns (add in a source) it gives org.postgresql.util.PSQLException: ERROR: column "column_name" does not exist.
Because in a target DB does not exist this column.
With best regards.

**Comment by tbrugz** [comment]
You may compare only the columns avaiable in both tables with:

`sqldiff.datadiff.usecommoncolumns=true`

You may also use *Diff2Queries* to have more control of the queries being diffed, see: https://github.com/tbrugz/sqldump/blob/master/diff2q.template.properties
